name: Docker Image CI/CD

on:
  pull_request:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    
    - name: Check docker installed or not
      run: docker run hello-world
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with: 
        username: ${{secrets.DOCKER_HUB_USERNAME}}
        password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
        
    - name: Build and push 
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mussaeb/app:dev-${{ github.sha }}
    
    
        
        
