name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check docker installed or not
      run: docker run hello-world
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with: 
        username: ${{secrets.DOCKER_HUB_USERNAME}}
        password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
    - name: set lower case owner name 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
    - name: Push to docker hub
      uses: docker/build-push-action/@v2
      with:
#        username: ${{secrets.DOCKER_USERNAME}}
#        password: ${{secrets.DOCKER_PASSWORD}}
#        repository: ${{secrets.DOCKERHUB_REPO}}
#        tag_with_ref: true  
       push: true
#       tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:latest
        
        
