
name: Minikube CI/CD
on: 
  push: 
    branches:
      - master
      
  pull_request:
    branches:
      - master

jobs:
  job1:
    runs-on: ubuntu-latest
    name: build and deploy to minikube
    steps:
    
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2

     - name: Login to Docker Hub
       uses: docker/login-action@v1
       with: 
         username: ${{secrets.DOCKER_HUB_USERNAME}}
         password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

     - name: Build and push to Docker hub 
       uses: docker/build-push-action@v3
       with:
         push: true 
         tags: mussaeb/flassk_image:latest

     - uses: actions/checkout@v2
     - name: Start minikube
       uses: medyagh/setup-minikube@master

     - name: Try the cluster !

       run: kubectl get pods -A

     - name: pull and load image from dockerhub
       run: minikube image load ${{secrets.DOCKER_HUB_USERNAME}}/flask_image
        

     - name: Deploy to kubernetes

       run:

        kubectl apply -f Deployment.yml

     - name: Test service URLs

       run: |

        minikube service list
        
        kubectl get all
        
        minikube service flask-app-service

        kubectl get services
        
        echo "------------------opening the service------------------"

        curl $(minikube service flask-app-service --url)
